// Fourth Stage B7: storage-operations module — read-only probing, VACUUM INTO
// consistent backup (frozen approach, adjudication #87), integrity/foreign-key
// checks and bounded retention pruning (adjudication #89).
//
// SQL red-line narrow contract (adjudication #86): this file may only contain
// compile-time-fixed storage-operations SQL — PRAGMA user_version / quick_check /
// integrity_check / foreign_key_check reads, VACUUM INTO and BEGIN/COMMIT/ROLLBACK.
// No business CRUD, no dynamic SQL, no model/web text. The VACUUM INTO target
// path is generated by the main process, strictly validated (absolute, inside the
// backups directory, strict naming pattern, not a link) and bound as a prepared
// statement parameter — `VACUUM INTO ?` parameter binding verified working on
// node:sqlite (Node 24.18.0 / SQLite 3.53.1, this task, 2026-08-15).
//
// Retention (adjudication #89): only strictly-named, regular, non-link files
// inside the backups directory are ever handled; keep the newest 5 and drop any
// older than 30 days (both upper bounds apply). The original database and any
// unrelated files are never touched; links are never followed.
//
// B7 hardening (2026-08-15 incident-recovery review, red→green):
// 1. Header probing reads a fixed 16 bytes via open/read/close — never
//    readFileSync whole-file (unbounded memory/IO on large databases).
// 2. Backup targets that already exist are rejected fail-closed — never
//    deletes/overwrites pre-existing files.
// 3. Target collisions retry with a fresh name (bounded); all attempts
//    colliding → fail-closed. Never remove an existing valid backup.
// 4. The backups directory is resolved via realpath (symlink/junction
//    traversal rejected): the resolved directory must stay inside the resolved
//    Sources directory; pruning never follows directory links out of bounds.
// 5. pruneBackups validates keepCount/maxAgeMs/nowMs (finite, non-negative
//    integers); invalid options → safe empty result, zero deletion.
//
// B7 audit remediation (2026-08-15 independent audit P2 race, red→green,
// decision #92): the old sequence 「lstat says absent → VACUUM INTO → rmSync on
// failure」 could delete a file created concurrently between the lstat check and
// the VACUUM. existsSync/lstatSync checks are for rejection/diagnostics only —
// never ownership proof for a later rmSync. New contract:
// 1. Two-phase publish: VACUUM INTO writes ONLY to a private staging path
//    (mkdtemp-created, exclusively owned by this call, inside the verified
//    backups directory); snapshot verification happens on the staging file.
// 2. After verification, publish to the strictly-named final path with an
//    atomic no-clobber primitive (hard link — target exists → EEXIST, never
//    overwrites; verified on Node 24.18.0 / Windows NTFS, 2026-08-15). Staging
//    and final live in the same directory tree → same volume.
// 3. Collision (EEXIST) → fresh name, bounded retries; exhausted → fail-closed
//    keeping the colliding file's original bytes. Any other publish error →
//    fail-closed immediately.
// 4. Failure cleanup touches only what this call provably created: the staging
//    file (rmSync single file) and the empty staging directory (rmdirSync —
//    non-empty leftovers stay visible; never recursively delete unknown
//    content).
// 5. createConsistentBackupAt no longer exists as a public arbitrary-path
//    entry point — production callers only ever use createConsistentBackup.
import { randomBytes } from 'node:crypto';
import {
  closeSync,
  existsSync,
  linkSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  openSync,
  readSync,
  readdirSync,
  realpathSync,
  rmdirSync,
  rmSync,
} from 'node:fs';
import { dirname, isAbsolute, join, resolve, sep } from 'node:path';
import { DatabaseSync } from 'node:sqlite';

// 严格命名模式（决议 #89）：主进程生成的时间戳 + 迁移前版本 + 随机后缀。
// 例：sources-backup-2026-08-15T09-12-33-456Z-v0-a1b2c3d4.db
// D4 最小泛化：前缀参数化（Watch 独立命名 watch-backup-…；Sources 前缀与行为
// 恒等——既有测试零改动通过）。
const BACKUP_PREFIX_PATTERN = /^[a-z0-9]+-backup-$/i;

export const BACKUP_NAME_PATTERN = buildBackupNamePattern('sources-backup-');
export const BACKUP_KEEP_COUNT = 5; // 最多保留最新 5 个（决议 #89）
export const BACKUP_MAX_AGE_MS = 30 * 24 * 60 * 60 * 1000; // 超过 30 天即清理（决议 #89）
const BACKUP_NAME_RETRY = 5; // 目标名碰撞时重新生成新名的最大次数（fail-closed 上界）

// 从受控前缀生成严格命名模式（前缀经正则转义——非受控字符不可能成为匹配语义）
export function buildBackupNamePattern(prefix: string): RegExp {
  if (typeof prefix !== 'string' || !BACKUP_PREFIX_PATTERN.test(prefix)) {
    throw new Error(`备份命名前缀非法（必须为 <标识>-backup- 形态）：${String(prefix)}`);
  }
  const escaped = prefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(
    `^${escaped}(\\d{4}-\\d{2}-\\d{2}T\\d{2}-\\d{2}-\\d{2}(?:-\\d{3})?Z)-v(\\d+)-[0-9a-f]{8}\\.db$`,
  );
}

const SQLITE_MAGIC = Buffer.from('SQLite format 3\0', 'latin1');
const SQL_VACUUM_INTO = 'VACUUM INTO ?'; // 路径参数绑定（实测支持；决议 #86）

// 主进程生成备份文件名（时间戳 + 迁移前版本 + 8 位随机 hex——同毫秒不碰撞）。
// randomHex 为测试注入点（碰撞语义确定性验证；缺省 crypto 随机）。
export function buildBackupFileName(
  version: number,
  nowMs: number,
  randomHex: () => string = () => randomBytes(4).toString('hex'),
  prefix: string = 'sources-backup-',
): string {
  if (typeof prefix !== 'string' || !BACKUP_PREFIX_PATTERN.test(prefix)) {
    throw new Error(`备份命名前缀非法（必须为 <标识>-backup- 形态）：${String(prefix)}`);
  }
  const ts = new Date(nowMs).toISOString().replace(/[:.]/g, '-');
  return `${prefix}${ts}-v${version}-${randomHex()}.db`;
}

// 从严格命名解析时间戳（决议 #89 清理排序/年龄判定；解析失败 → null 不处理）
export function parseBackupTimestamp(
  fileName: string,
  pattern: RegExp = BACKUP_NAME_PATTERN,
): number | null {
  const match = pattern.exec(fileName);
  if (match === null) return null;
  const parts = match[1]!.split(/[TZ-]/).map((p) => Number(p));
  // 形如 [y, m, d, h, mm, s(, ms)]
  if (parts.some((p) => !Number.isInteger(p))) return null;
  return Date.UTC(
    parts[0]!,
    parts[1]! - 1,
    parts[2]!,
    parts[3]!,
    parts[4]!,
    parts[5]!,
    parts.length > 6 ? parts[6]! : 0,
  );
}

// 备份目标路径校验（决议 #86/#89）：绝对路径、位于备份目录内（段边界判定）、
// 严格命名。返回值不含原始输入（只回传生成后的安全路径），失败原因仅固定中文文案。
export function validateBackupTarget(
  backupsDir: string,
  fileName: string,
  pattern: RegExp = BACKUP_NAME_PATTERN,
): { ok: true; path: string } | { ok: false; reason: string } {
  if (typeof fileName !== 'string' || !pattern.test(fileName)) {
    return { ok: false, reason: '备份文件名不符合严格命名规范' };
  }
  if (typeof backupsDir !== 'string' || !isAbsolute(backupsDir)) {
    return { ok: false, reason: '备份目录必须是绝对路径' };
  }
  const path = join(backupsDir, fileName);
  if (!isPathInside(path, backupsDir)) {
    return { ok: false, reason: '备份目标必须位于备份目录内' };
  }
  return { ok: true, path };
}

// 解析最近存在祖先的真实路径并拼接剩余段（backups 目录可能尚未创建）。
// 全部祖先缺失（如盘符异常）→ 返回规范化原路径，由调用方包含性判定兜底拒绝。
function resolveRealPathBest(path: string): string {
  let current = path;
  const suffix: string[] = [];
  for (;;) {
    try {
      return join(realpathSync(current), ...[...suffix].reverse());
    } catch {
      const parent = dirname(current);
      if (parent === current) return resolve(path);
      suffix.push(current.slice(parent.length + 1));
      current = parent;
    }
  }
}

// 包含性判定（Windows 大小写不敏感 + 段边界——防 'backups2' 前缀歧义）
function isPathInside(child: string, parent: string): boolean {
  const c = resolve(child).toLowerCase();
  const p = resolve(parent).toLowerCase();
  return c === p || c.startsWith(p.endsWith(sep) ? p : p + sep);
}

// 固定 16 字节文件头读取（不整库读入内存——大库无界内存/磁盘压力红线；
// 句柄 finally 可靠关闭）。读取失败 → null（调用方按不可打开处理）。
function readSqliteHeader(dbPath: string): Buffer | null {
  let fd: number;
  try {
    fd = openSync(dbPath, 'r');
  } catch {
    return null;
  }
  try {
    const header = Buffer.alloc(16);
    let offset = 0;
    while (offset < 16) {
      const n = readSync(fd, header, offset, 16 - offset, offset);
      if (n === 0) break; // EOF 提前（短文件）
      offset += n;
    }
    return header;
  } finally {
    closeSync(fd);
  }
}

// ---------- 只读探测（启动顺序契约：先探测版本与完整性，不修改原库） ----------

export type DbProbeState = 'missing' | 'bad-magic' | 'unopenable' | 'not-a-file' | 'ok';

export interface DbProbe {
  state: DbProbeState;
  userVersion: number | null;
  reason: string | null; // 中文分类原因（不含绝对路径细节——恢复态 UI 用安全标签）
}

// 探测（决议 #86）：文件头 magic + 只读连接打开 + PRAGMA user_version。
// 只读连接不写任何内容（SQLite 只读打开不创建 -wal/-shm、不执行 journal 恢复写入
// ——写操作在只读连接上确定性失败，本任务实测）。未知高版本在迁移前判定，
// 绝不先以 WAL 写连接打开原库。文件头仅读取固定 16 字节（B7 加固 #1）。
export function probeDbFile(dbPath: string): DbProbe {
  let stat;
  try {
    stat = lstatSync(dbPath);
  } catch {
    return { state: 'missing', userVersion: null, reason: null };
  }
  if (stat.isSymbolicLink() || !stat.isFile()) {
    // 目录/链接等形态 = 环境配置类问题（非数据损坏）——调用方按不可用处理
    return { state: 'not-a-file', userVersion: null, reason: '数据库路径不是普通文件' };
  }
  if (stat.size < 16) {
    // 空文件/超短文件 = 截断形态（决议 #88 校准：原路径保留，进入恢复态）
    return { state: 'bad-magic', userVersion: null, reason: '数据库文件过短（可能被截断）' };
  }
  const header = readSqliteHeader(dbPath);
  if (header === null || !header.equals(SQLITE_MAGIC)) {
    return {
      state: 'bad-magic',
      userVersion: null,
      reason: '数据库文件头无效（不是 SQLite 数据库）',
    };
  }
  let db: DatabaseSync;
  try {
    db = new DatabaseSync(dbPath, { readOnly: true });
  } catch {
    return { state: 'unopenable', userVersion: null, reason: '数据库无法打开（可能已损坏）' };
  }
  try {
    const row = db.prepare('PRAGMA user_version').get() as { user_version: unknown };
    if (!Number.isInteger(row.user_version)) {
      return { state: 'unopenable', userVersion: null, reason: '数据库版本号非法' };
    }
    return { state: 'ok', userVersion: row.user_version as number, reason: null };
  } catch {
    return { state: 'unopenable', userVersion: null, reason: '数据库无法读取（可能已损坏）' };
  } finally {
    db.close();
  }
}

// 快速完整性检查（只读连接；当前版本库启动时执行——失败进入只读恢复态）
export function quickCheckDb(dbPath: string): { ok: boolean; reason: string | null } {
  let db: DatabaseSync;
  try {
    db = new DatabaseSync(dbPath, { readOnly: true });
  } catch {
    return { ok: false, reason: '数据库无法打开（可能已损坏）' };
  }
  try {
    const row = db.prepare('PRAGMA quick_check').get() as Record<string, unknown>;
    const value = String(Object.values(row)[0] ?? '');
    return value === 'ok'
      ? { ok: true, reason: null }
      : { ok: false, reason: '数据库快速完整性检查未通过' };
  } catch {
    return { ok: false, reason: '数据库快速完整性检查失败' };
  } finally {
    db.close();
  }
}

export interface DbIntegrityResult {
  ok: boolean;
  integrity: string; // integrity_check 首行结果（'ok' = 通过）
  foreignKeyViolations: number; // PRAGMA foreign_key_check 命中行数
  reason: string | null;
}

// 迁移后完整性 + 外键检查（只读连接；失败 → 调用方进入只读恢复态，不覆盖原库）
export function checkDbIntegrity(dbPath: string): DbIntegrityResult {
  let db: DatabaseSync;
  try {
    db = new DatabaseSync(dbPath, { readOnly: true });
  } catch {
    return {
      ok: false,
      integrity: 'unopenable',
      foreignKeyViolations: -1,
      reason: '数据库无法打开',
    };
  }
  try {
    const row = db.prepare('PRAGMA integrity_check').get() as Record<string, unknown>;
    const integrity = String(Object.values(row)[0] ?? '');
    const violations = db.prepare('PRAGMA foreign_key_check').all().length;
    return {
      ok: integrity === 'ok' && violations === 0,
      integrity,
      foreignKeyViolations: violations,
      reason: integrity !== 'ok' ? '完整性检查未通过' : violations > 0 ? '外键检查发现违例' : null,
    };
  } catch {
    return {
      ok: false,
      integrity: 'error',
      foreignKeyViolations: -1,
      reason: '完整性检查执行失败',
    };
  } finally {
    db.close();
  }
}

// ---------- 一致性备份（决议 #87：VACUUM INTO 主路径；B7 加固 #2/#3；
// 独立审计 P2 竞态修复：两阶段 staging + no-clobber 发布，决议 #92） ----------

export interface BackupResult {
  ok: boolean;
  backupPath: string | null; // 失败时为 null（本次 staging 已精确清理，零残留）
  reason: string | null;
}

// 私有 staging 命名（决议 #92）：目录名不匹配严格命名模式（prune 永不处理
// staging 残留——纵深防御）；snapshot.db 为本调用 VACUUM INTO 的唯一目标文件。
const STAGING_DIR_PREFIX = 'staging-';
const STAGING_FILE_NAME = 'snapshot.db';

// 内部实现（不导出——任意路径入口不复存在，决议 #92）：对源库执行 VACUUM INTO
// 到调用方所有的私有 staging 路径并校验快照（可打开 + integrity ok +
// user_version 与预期迁移前版本一致）。本函数绝不删除/覆盖任何文件——staging
// 清理由调用方按所有权执行。源库以只读连接打开（备份过程绝不写源库——WAL
// 活跃时仅读取一致性快照）；existsSync 仅用于拒绝/诊断，不构成任何所有权证明。
function vacuumIntoStaging(
  dbPath: string,
  stagingPath: string,
  expectedVersion: number,
): { ok: boolean; reason: string | null } {
  // 源库缺失 → 失败（绝不因备份而创建数据库文件）
  if (!existsSync(dbPath)) {
    return { ok: false, reason: '备份失败：源数据库不存在' };
  }
  let source: DatabaseSync;
  try {
    source = new DatabaseSync(dbPath, { readOnly: true });
  } catch {
    return { ok: false, reason: '备份失败：源数据库无法打开' };
  }
  try {
    source.prepare(SQL_VACUUM_INTO).run(stagingPath);
  } catch {
    // 不删除任何文件：staging 路径归调用方所有，由调用方按所有权精确清理
    return { ok: false, reason: '备份失败：VACUUM INTO 执行失败' };
  } finally {
    source.close();
  }
  // 快照校验（一致性备份必须可打开且完整；失败 → 调用方清理本次 staging）
  let snapshot: DatabaseSync;
  try {
    snapshot = new DatabaseSync(stagingPath, { readOnly: true });
  } catch {
    return { ok: false, reason: '备份失败：快照无法打开' };
  }
  try {
    const integrity = snapshot.prepare('PRAGMA integrity_check').get() as Record<string, unknown>;
    const version = snapshot.prepare('PRAGMA user_version').get() as { user_version: unknown };
    if (String(Object.values(integrity)[0] ?? '') !== 'ok') {
      return { ok: false, reason: '备份失败：快照完整性检查未通过' };
    }
    if (version.user_version !== expectedVersion) {
      return { ok: false, reason: '备份失败：快照版本与迁移前版本不符' };
    }
    return { ok: true, reason: null };
  } catch {
    return { ok: false, reason: '备份失败：快照校验未通过' };
  } finally {
    // Windows：后续清理前必须先关闭只读句柄（否则 EPERM）
    snapshot.close();
  }
}

// 便捷入口（生产唯一备份入口，决议 #92）：主进程生成严格命名 + 校验目标路径 +
// 建目录 + 两阶段 staging 发布。备份目录解析后必须仍位于源库所在目录（Sources
// 目录）内（symlink/junction 越界拒绝）。发布契约：VACUUM INTO 只写本次调用
// 独占的私有 staging 目录（mkdtemp 原子创建，位于已验证 backups 目录内）；
// 快照校验通过后以硬链接 no-clobber 原子发布到严格命名的最终路径（目标已存在
// → EEXIST 原子失败绝不覆盖——Node 24/Windows 实测，本任务 2026-08-15——换
// 新名有界重试，全部碰撞 fail-closed；其他错误 fail-closed 不重试）；失败仅
// 精确清理本次创建的 staging 文件与空目录（rmSync 单一文件 + rmdirSync 空目录
// ——非空残留保留现场，绝不递归删除未知内容）。randomHex 为测试注入点（缺省
// crypto 随机）。
export function createConsistentBackup(
  dbPath: string,
  backupsDir: string,
  version: number,
  nowMs: () => number,
  randomHex?: () => string,
  options: { namePrefix?: string; parentLabel?: string } = {},
): BackupResult {
  const namePrefix = options.namePrefix ?? 'sources-backup-';
  const parentLabel = options.parentLabel ?? '信源';
  const pattern = buildBackupNamePattern(namePrefix);
  const basic = validateBackupTarget(
    backupsDir,
    buildBackupFileName(version, nowMs(), randomHex, namePrefix),
    pattern,
  );
  if (!basic.ok) return { ok: false, backupPath: null, reason: basic.reason };
  // 目录真实路径校验：backups 解析后必须仍位于源库目录内
  const sourcesReal = resolveRealPathBest(dirname(dbPath));
  const backupsReal = resolveRealPathBest(backupsDir);
  if (!isPathInside(backupsReal, sourcesReal)) {
    return { ok: false, backupPath: null, reason: `备份目录必须位于${parentLabel}数据目录内` };
  }
  try {
    mkdirSync(backupsReal, { recursive: true });
  } catch {
    return { ok: false, backupPath: null, reason: '备份失败：备份目录无法创建' };
  }
  // 私有 staging 目录：mkdtemp 原子独占创建（本次调用所有权证明）
  let stagingDir: string;
  try {
    stagingDir = mkdtempSync(join(backupsReal, STAGING_DIR_PREFIX));
  } catch {
    return { ok: false, backupPath: null, reason: '备份失败：staging 目录无法创建' };
  }
  const stagingPath = join(stagingDir, STAGING_FILE_NAME);
  // 所有权清理：仅删除本次创建的 staging 文件与空目录；目录非空（理论并发异常
  // 写入）→ rmdirSync 失败保留现场，绝不递归删除未知内容
  const cleanupStaging = (): void => {
    try {
      rmSync(stagingPath, { force: true });
    } catch {
      // 清理失败不掩盖原始错误
    }
    try {
      rmdirSync(stagingDir);
    } catch {
      // 非空残留保留现场（不递归删除）
    }
  };
  // 阶段 1：VACUUM INTO 只写 staging + 快照校验（失败 → 精确清理本次 staging）
  const vacuum = vacuumIntoStaging(dbPath, stagingPath, version);
  if (!vacuum.ok) {
    cleanupStaging();
    return { ok: false, backupPath: null, reason: vacuum.reason };
  }
  // 阶段 2：no-clobber 原子发布（硬链接——staging 与最终路径同目录必然同卷）
  for (let attempt = 0; attempt < BACKUP_NAME_RETRY; attempt += 1) {
    const candidate = validateBackupTarget(
      backupsReal,
      buildBackupFileName(version, nowMs(), randomHex, namePrefix),
      pattern,
    );
    if (!candidate.ok) {
      cleanupStaging();
      return { ok: false, backupPath: null, reason: candidate.reason };
    }
    try {
      linkSync(stagingPath, candidate.path);
      cleanupStaging(); // 发布成功：移除本次 staging 链接（最终文件字节不变）
      return { ok: true, backupPath: candidate.path, reason: null };
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'EEXIST') {
        cleanupStaging();
        return { ok: false, backupPath: null, reason: '备份失败：最终文件发布失败' };
      }
      // EEXIST = 最终名已被并发占用 → 保留其原始字节，换新名重试（有界）
    }
  }
  cleanupStaging();
  return { ok: false, backupPath: null, reason: '备份失败：目标命名冲突（请稍后重试）' };
}

// ---------- 有界保留清理（决议 #89；B7 加固 #4/#5） ----------

export interface PruneBackupsResult {
  removed: string[]; // 被删除的备份文件名
  kept: string[]; // 保留的备份文件名（诊断用）
}

// 仅处理严格命名 + 普通文件 + 非链接；排序按解析时间戳升序、同名按全名（随机
// 后缀收尾确定性）；保留最新 keepCount 且年龄 ≤ maxAgeMs 的条目，其余删除。
// 原库与任何无关文件/目录/链接一律不动；不跟随链接（含 backups 目录本身为
// symlink/junction 时安全空结果）。
export function pruneBackups(
  backupsDir: string,
  options: {
    keepCount?: number;
    maxAgeMs?: number;
    nowMs?: number;
    sourcesDir?: string;
    namePattern?: RegExp; // D4 最小泛化：Watch 独立命名模式（缺省 Sources 恒等）
  } = {},
): PruneBackupsResult {
  const keepCount = options.keepCount ?? BACKUP_KEEP_COUNT;
  const maxAgeMs = options.maxAgeMs ?? BACKUP_MAX_AGE_MS;
  const nowMs = options.nowMs ?? Date.now();
  const pattern = options.namePattern ?? BACKUP_NAME_PATTERN;
  // 参数边界验证（fail-closed）：非有限/负数/非整数参数拒绝处理——安全空结果，
  // 绝不因异常参数触发批量误删
  if (
    !Number.isSafeInteger(keepCount) ||
    keepCount < 0 ||
    !Number.isSafeInteger(maxAgeMs) ||
    maxAgeMs < 0 ||
    !Number.isFinite(nowMs)
  ) {
    return { removed: [], kept: [] };
  }
  // 目录真实路径校验：backups 目录本身为链接/非目录 → 安全空结果（绝不跟随
  // 链接枚举/删除）；解析后必须仍位于 sourcesDir（若提供）内
  let realBackups: string;
  try {
    const dirStat = lstatSync(backupsDir);
    if (!dirStat.isDirectory() || dirStat.isSymbolicLink()) {
      return { removed: [], kept: [] };
    }
    realBackups = realpathSync(backupsDir);
  } catch {
    return { removed: [], kept: [] }; // 目录不存在/不可达 → 安全空结果
  }
  if (options.sourcesDir !== undefined) {
    const realSources = resolveRealPathBest(options.sourcesDir);
    if (!isPathInside(realBackups, realSources)) return { removed: [], kept: [] };
  }
  let entries: string[];
  try {
    entries = readdirSync(realBackups);
  } catch {
    return { removed: [], kept: [] }; // 枚举失败 → 安全空结果
  }
  const candidates = entries
    .filter((name) => pattern.test(name))
    .filter((name) => {
      try {
        const st = lstatSync(join(realBackups, name));
        return st.isFile() && !st.isSymbolicLink();
      } catch {
        return false; // 已消失/不可达 → 不处理
      }
    })
    .map((name) => ({ name, ts: parseBackupTimestamp(name, pattern) ?? 0 }))
    .sort((a, b) => (a.ts !== b.ts ? a.ts - b.ts : a.name.localeCompare(b.name)));
  const removed: string[] = [];
  const kept: string[] = [];
  const keepFrom = Math.max(0, candidates.length - keepCount); // 最新 keepCount 个
  candidates.forEach((entry, index) => {
    const expired = nowMs - entry.ts > maxAgeMs;
    if (index >= keepFrom && !expired) {
      kept.push(entry.name);
      return;
    }
    const fullPath = join(realBackups, entry.name);
    try {
      // 删除前复核（TOCTOU 防御）：仍为目录内普通文件（非链接）且真实路径未越界
      const st = lstatSync(fullPath);
      if (!st.isFile() || st.isSymbolicLink()) return;
      if (!isPathInside(realpathSync(fullPath), realBackups)) return;
      rmSync(fullPath, { force: true });
      removed.push(entry.name);
    } catch {
      // 删除失败（锁占用等）：保留现场，不抛异常（清理为最佳努力）
    }
  });
  return { removed, kept };
}
