import { readFile } from 'node:fs/promises';
import { isAbsolute, relative, resolve } from 'node:path';

export const APP_ASSET_SCHEME = 'aibrowse';
export const APP_ASSET_HOST = 'app';
export const APP_ENTRY_URL = 'aibrowse://app/index.html';

export const APP_ASSET_CSP = [
  "default-src 'none'",
  "script-src 'self'",
  "style-src 'self'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'none'",
  "frame-src 'none'",
  "child-src 'none'",
  "worker-src 'none'",
  "object-src 'none'",
  "form-action 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "manifest-src 'self'",
  "media-src 'none'",
].join('; ');

export interface AppAssetManifestEntry {
  /** POSIX-style path relative to the packaged renderer asset root. */
  readonly file: string;
  /** Fixed build-time MIME value, including charset where appropriate. */
  readonly contentType: string;
}

/** Generated by the release build from the actual renderer output. */
export interface AppAssetManifest {
  readonly version: 1;
  readonly assets: Readonly<Record<string, AppAssetManifestEntry>>;
}

export interface SchemeRegistrar {
  registerSchemesAsPrivileged(schemes: Electron.CustomScheme[]): void;
}

export interface AssetProtocolTarget {
  isProtocolHandled(scheme: string): boolean;
  handle(scheme: string, handler: (request: Request) => Response | Promise<Response>): void;
}

interface AssetRequest {
  readonly url: string;
  readonly method: string;
}

type AssetHandler = (request: AssetRequest) => Promise<Response>;

const installedTargets = new WeakSet<object>();
const CONTENT_TYPE_PATTERN =
  /^[a-z0-9][a-z0-9!#$&^_.+-]*\/[a-z0-9][a-z0-9!#$&^_.+-]*(?:; charset=[a-z0-9._-]+)?$/i;

export function registerAppAssetScheme(target: SchemeRegistrar): void {
  target.registerSchemesAsPrivileged([
    {
      scheme: APP_ASSET_SCHEME,
      privileges: {
        standard: true,
        secure: true,
        supportFetchAPI: true,
        bypassCSP: false,
        allowServiceWorkers: false,
        allowExtensions: false,
      },
    },
  ]);
}

export function installAppAssetProtocol(
  target: AssetProtocolTarget,
  assetRoot: string,
  manifest: AppAssetManifest,
): void {
  if (installedTargets.has(target)) throw new Error('aibrowse 资产协议已装配');
  if (target.isProtocolHandled(APP_ASSET_SCHEME)) throw new Error('aibrowse 资产协议已被占用');
  const handler = createAppAssetHandler(assetRoot, manifest);
  target.handle(APP_ASSET_SCHEME, handler);
  installedTargets.add(target);
}

export function createAppAssetHandler(assetRoot: string, manifest: AppAssetManifest): AssetHandler {
  const assets = validateAndResolveManifest(assetRoot, manifest);
  return async (request): Promise<Response> => {
    if (request.method !== 'GET' && request.method !== 'HEAD') return emptyResponse(405);
    const path = resolveManifestPath(request.url);
    if (path === null) return emptyResponse(404);
    const asset = assets.get(path);
    if (asset === undefined) return emptyResponse(404);
    try {
      const body =
        request.method === 'HEAD' ? null : new Uint8Array(await readFile(asset.absoluteFile));
      return new Response(body, { status: 200, headers: responseHeaders(asset.contentType) });
    } catch {
      return emptyResponse(404);
    }
  };
}

function resolveManifestPath(rawUrl: string): string | null {
  // Validate syntax before URL canonicalization so encoded dot segments cannot turn
  // into an allowed manifest key after normalization.
  const match = rawUrl.match(/^([a-z][a-z0-9+.-]*):\/\/([^/?#]*)([^?#]*)(?:\?[^#]*)?(?:#.*)?$/i);
  if (match === null) return null;
  const [, rawScheme, rawAuthority, rawPath] = match;
  if (
    rawScheme?.toLowerCase() !== APP_ASSET_SCHEME ||
    rawAuthority !== APP_ASSET_HOST ||
    rawPath === undefined ||
    !isCanonicalUrlPath(rawPath)
  ) {
    return null;
  }
  try {
    const parsed = new URL(rawUrl);
    if (
      parsed.protocol !== `${APP_ASSET_SCHEME}:` ||
      parsed.hostname !== APP_ASSET_HOST ||
      parsed.username !== '' ||
      parsed.password !== '' ||
      parsed.port !== '' ||
      parsed.pathname !== rawPath
    ) {
      return null;
    }
    return parsed.pathname;
  } catch {
    return null;
  }
}

function validateAndResolveManifest(
  assetRoot: string,
  manifest: AppAssetManifest,
): ReadonlyMap<string, { absoluteFile: string; contentType: string }> {
  if (manifest.version !== 1 || typeof manifest.assets !== 'object' || manifest.assets === null) {
    throw new Error('资产 manifest 版本或结构无效');
  }
  const absoluteRoot = resolve(assetRoot);
  const resolved = new Map<string, { absoluteFile: string; contentType: string }>();
  for (const [urlPath, entry] of Object.entries(manifest.assets)) {
    if (!isCanonicalUrlPath(urlPath) || typeof entry !== 'object' || entry === null) {
      throw new Error('资产 manifest 路径无效');
    }
    if (!isCanonicalRelativeFile(entry.file) || !CONTENT_TYPE_PATTERN.test(entry.contentType)) {
      throw new Error('资产 manifest 条目无效');
    }
    const absoluteFile = resolve(absoluteRoot, ...entry.file.split('/'));
    const fromRoot = relative(absoluteRoot, absoluteFile);
    if (fromRoot === '' || fromRoot.startsWith('..') || isAbsolute(fromRoot)) {
      throw new Error('资产 manifest 文件越界');
    }
    resolved.set(urlPath, { absoluteFile, contentType: entry.contentType });
  }
  if (!resolved.has('/index.html')) throw new Error('资产 manifest 缺少入口');
  return resolved;
}

function isCanonicalUrlPath(value: string): boolean {
  if (!value.startsWith('/') || value.length < 2) return false;
  if (
    value.includes('\\') ||
    value.includes('\0') ||
    value.includes(':') ||
    value.startsWith('//')
  ) {
    return false;
  }
  return value
    .slice(1)
    .split('/')
    .every((segment) => /^[a-z0-9._-]+$/i.test(segment) && segment !== '.' && segment !== '..');
}

function isCanonicalRelativeFile(value: string): boolean {
  if (
    value === '' ||
    value.includes('%') ||
    value.includes('\\') ||
    value.includes('\0') ||
    value.includes(':')
  ) {
    return false;
  }
  if (value.startsWith('/') || isAbsolute(value)) return false;
  return value
    .split('/')
    .every((segment) => /^[a-z0-9._-]+$/i.test(segment) && segment !== '.' && segment !== '..');
}

function responseHeaders(contentType: string): Headers {
  return new Headers({
    'content-type': contentType,
    'content-security-policy': APP_ASSET_CSP,
    'x-content-type-options': 'nosniff',
    'cross-origin-resource-policy': 'same-origin',
    'cache-control': 'no-store',
  });
}

function emptyResponse(status: number): Response {
  return new Response(null, {
    status,
    headers: responseHeaders('text/plain; charset=utf-8'),
  });
}
